import{loadVenues,categories,featureLabels}from'./core.js';
import{getAudits,getCustomLocations,getAdminLog,saveLocation,addLocation,deleteLocation,moderateAudit,exportAdminData,importAdminData}from'./admin-store.js';
import{clearCache}from'./osm-api.js';
import{getBusinesses,seedBusinessData,migrateSeedBusinessLocations,getBusinessForLocation,addBusinessReview}from'./business-store.js';
import{fetchRemoteAudits,pushRemoteModeration,mergeAudits,isBackendConfigured}from'./audit-backend.js';
seedBusinessData();migrateSeedBusinessLocations();
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];let venues=[],auditFilter='pending',deleteTarget=null;
const esc=s=>{const d=document.createElement('div');d.textContent=s??'';return d.innerHTML};
const toast=m=>{const t=$('#toast');t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800)};
function showView(name){$$('.admin-view').forEach(v=>v.classList.toggle('active',v.id===`view-${name}`));$$('.admin-nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view===name));if(name==='locations')renderLocations();if(name==='audits')renderAudits();if(name==='businesses')renderBusinesses();if(name==='activity')renderActivity()}
$$('.admin-nav-item').forEach(b=>b.onclick=()=>showView(b.dataset.view));$$('[data-go]').forEach(b=>b.onclick=()=>showView(b.dataset.go));
async function reload(){try{venues=await loadVenues();await syncRemoteAudits();renderAll()}catch(e){toast(e.message)}}
async function syncRemoteAudits(){if(!isBackendConfigured())return;const remote=await fetchRemoteAudits();if(!remote.length)return;const merged=mergeAudits(getAudits(),remote);localStorage.setItem('akseskota_audits',JSON.stringify(merged));toast(`${remote.length} audit bersama dimuat`)}
function renderAll(){const audits=getAudits(),pending=audits.filter(a=>(a.status||'pending')==='pending').length;$('#stat-locations').textContent=venues.length;$('#stat-custom').textContent=getCustomLocations().filter(x=>!x.deleted).length;$('#stat-pending').textContent=pending;$('#stat-approved').textContent=audits.filter(a=>a.status==='approved').length;$('#pending-badge').textContent=pending||'';$('#recent-audits').innerHTML=audits.slice(-5).reverse().map(a=>auditMini(a)).join('')||'<p class="empty">Belum ada audit.</p>';renderLocations();renderAudits();renderActivity()}
function auditMini(a){return`<div class="mini-row"><div><strong>${esc(a.locationName)}</strong><small>${new Date(a.timestamp).toLocaleString('id-ID')}</small></div><span class="status ${a.status||'pending'}">${statusLabel(a.status)}</span></div>`}
const statusLabel=s=>({approved:'Disetujui',rejected:'Ditolak',pending:'Menunggu'}[s||'pending']);
function renderLocations(){const q=$('#location-search').value.toLowerCase(),cat=$('#location-category').value;const rows=venues.filter(v=>(cat==='all'||v.category===cat)&&(!q||v.name.toLowerCase().includes(q)||(v.address||'').toLowerCase().includes(q)||v.id.includes(q))).slice(0,250);$('#locations-body').innerHTML=rows.map(v=>`<tr><td><strong>${esc(v.name)}</strong><small>${esc(v.address||v.id)}</small></td><td><span class="category-pill">${categories[v.category]?.label||v.category}</span></td><td>${esc(v.source||'OpenStreetMap')}</td><td><code>${v.lat.toFixed(5)}, ${v.lng.toFixed(5)}</code></td><td><div class="row-actions"><button data-edit="${v.id}">Edit</button><button class="delete" data-delete="${v.id}">Hapus</button></div></td></tr>`).join('')||'<tr><td colspan="5" class="empty">Tidak ada lokasi.</td></tr>';$$('[data-edit]').forEach(b=>b.onclick=()=>openLocation(venues.find(v=>v.id===b.dataset.edit)));$$('[data-delete]').forEach(b=>b.onclick=()=>confirmDelete(venues.find(v=>v.id===b.dataset.delete)))}
$('#location-search').oninput=renderLocations;$('#location-category').onchange=renderLocations;
function openLocation(v=null){$('#location-form').reset();$('#loc-id').value=v?.id||'';$('#loc-name').value=v?.name||'';$('#loc-address').value=v?.address||'';$('#loc-category').value=v?.category||'wheelchair_ramp';$('#loc-source').value=v?.source||'Admin lokal';$('#loc-lat').value=v?.lat??'';$('#loc-lng').value=v?.lng??'';$$('[data-loc-feature]').forEach(x=>x.checked=v?.attributes?.[x.dataset.locFeature]===true);$('#dialog-eyebrow').textContent=v?'Edit data':'Lokasi baru';$('#dialog-title').textContent=v?'Edit lokasi':'Tambah lokasi';$('#location-dialog').showModal()}
$$('[data-open-location]').forEach(b=>b.onclick=()=>openLocation());
$('#location-form').onsubmit=e=>{e.preventDefault();const id=$('#loc-id').value,data={name:$('#loc-name').value.trim(),address:$('#loc-address').value.trim(),category:$('#loc-category').value,lat:+$('#loc-lat').value,lng:+$('#loc-lng').value,source:$('#loc-source').value,attributes:Object.fromEntries($$('[data-loc-feature]').map(x=>[x.dataset.locFeature,x.checked]))};if(!data.name||!Number.isFinite(data.lat)||!Number.isFinite(data.lng))return;if(id)saveLocation({...data,id});else addLocation(data);$('#location-dialog').close();toast(id?'Lokasi diperbarui':'Lokasi ditambahkan');reload()};
function confirmDelete(v){deleteTarget=v;$('#confirm-text').textContent=`${v.name} akan disembunyikan dari peta pada perangkat ini.`;$('#confirm-dialog').showModal()}
$('#confirm-dialog').addEventListener('close',()=>{if($('#confirm-dialog').returnValue==='confirm'&&deleteTarget){deleteLocation(deleteTarget);toast('Lokasi dihapus');deleteTarget=null;reload()}});
function renderAudits(){const rows=getAudits().filter(a=>auditFilter==='all'||(a.status||'pending')===auditFilter);$('#audit-queue').innerHTML=rows.slice().reverse().map(a=>`<article class="audit-review"><div class="audit-review-head"><div><strong>${esc(a.locationName)}</strong><small>${new Date(a.timestamp).toLocaleString('id-ID')} · ${a.rating}/5</small></div><span class="status ${a.status||'pending'}">${statusLabel(a.status)}</span></div><div class="audit-features">${(a.features||[]).map(f=>`<span> ${featureLabels[f]||f}</span>`).join('')||'<span>Tidak ada fasilitas dipilih</span>'}</div>${a.image?.dataUrl?`<a class="audit-evidence" href="${a.image.dataUrl}" target="_blank" rel="noopener"><img src="${a.image.dataUrl}" alt="Bukti kondisi ${esc(a.locationName)}"><span>Lihat foto bukti </span></a>`:''}${a.explanation?`<div class="audit-explanation"><strong>Penjelasan kontributor</strong><p>${esc(a.explanation)}</p></div>`:''}<label>Catatan moderator<textarea data-note="${a.id}" placeholder="Alasan atau catatan internal">${esc(a.moderationNote||'')}</textarea></label><div class="review-actions"><button class="btn approve-btn" data-approve="${a.id}">Setujui</button><button class="btn reject-btn" data-reject="${a.id}">Tolak</button></div></article>`).join('')||'<div class="admin-card empty">Tidak ada audit pada status ini.</div>';$$('[data-approve]').forEach(b=>b.onclick=()=>moderate(b.dataset.approve,'approved'));$$('[data-reject]').forEach(b=>b.onclick=()=>moderate(b.dataset.reject,'rejected'))}
function moderate(id,status){const note=$(`[data-note="${id}"]`)?.value||'';const audit=moderateAudit(id,status,note);if(status==='approved'&&audit){const business=getBusinessForLocation(audit.locationId);if(business)addBusinessReview({locationId:audit.locationId,businessId:business.id,rating:audit.rating,features:audit.features,reviewerName:'Kontributor',auditId:audit.id})}pushRemoteModeration(id,status,note);toast(status==='approved'?'Audit disetujui':'Audit ditolak');renderAll()}
$$('[data-audit-filter]').forEach(b=>b.onclick=()=>{auditFilter=b.dataset.auditFilter;$$('[data-audit-filter]').forEach(x=>x.classList.toggle('active',x===b));renderAudits()});
function renderActivity(){$('#activity-list').innerHTML=getAdminLog().map(l=>`<div class="activity-row"><span>${new Date(l.timestamp).toLocaleString('id-ID')}</span><strong>${esc(l.action.replaceAll('_',' '))}</strong><span>${esc(l.target)}</span></div>`).join('')||'<p class="empty">Belum ada aktivitas admin.</p>'}
const bizBadge={platinum:'P',gold:'G',silver:'S',bronze:'B'};
function renderBusinesses(){const businesses=getBusinesses();$('#businesses-list').innerHTML=businesses.length?`<table class="admin-table"><thead><tr><th>Usaha</th><th>Lokasi</th><th>Badge</th><th>Skor</th><th>Review</th><th>Status</th></tr></thead><tbody>${businesses.map(b=>`<tr><td><strong>${esc(b.name)}</strong><small>${esc(b.ownerName||'—')}</small></td><td><small>${esc(b.locationId||'—')}</small></td><td><span class="business-badge badge-${b.badgeLevel||'bronze'}">${bizBadge[b.badgeLevel||'bronze']} ${b.badgeLevel||'bronze'}</span></td><td><strong>${b.score||0}</strong></td><td>${b.reviewCount||0}</td><td>${b.verified?'<span style="color:var(--green)"> Terverifikasi</span>':'<span style="color:var(--amber)">Menunggu</span>'}</td></tr>`).join('')}</tbody></table>`:'<p class="empty">Belum ada usaha terdaftar. Usaha dapat didaftarkan melalui halaman publik.</p>'}
$('#export-btn').onclick=()=>{const blob=new Blob([JSON.stringify(exportAdminData(),null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`akseskota-admin-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href)};
$('#import-file').onchange=async e=>{try{const data=JSON.parse(await e.target.files[0].text());importAdminData(data);toast('Backup berhasil diimpor');reload()}catch(err){toast(`Import gagal: ${err.message}`)}e.target.value=''};
$('#refresh-osm').onclick=()=>{clearCache();toast('Cache OSM dibersihkan');reload()};
await reload();
