import{shell,footer,initShell,initLogout,loadVenues,initAnimations}from'./core.js?v=5';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];$('#shell').innerHTML=shell('audit');$('#footer').innerHTML=footer();initShell();initLogout();initAnimations();
let rating=0,features=new Set(),venues=[],imageData=null;const select=$('#venue-select'),imageInput=$('#audit-image'),explanation=$('#audit-explanation');
function stats(){let audits=[];try{audits=JSON.parse(localStorage.getItem('akseskota_audits')||'[]')}catch{}const approved=audits.filter(a=>a.status==='approved').length,pending=audits.filter(a=>(a.status||'pending')==='pending').length;$('#score').textContent=`${approved*10} poin`;$('#audit-count').textContent=audits.length?`${approved} disetujui · ${pending} menunggu`:'Belum ada audit'}
function validate(){$('#submit').disabled=!(select.value&&rating)}
$$('.check-item').forEach(b=>b.onclick=()=>{const on=b.getAttribute('aria-pressed')!=='true';b.setAttribute('aria-pressed',on);on?features.add(b.dataset.feature):features.delete(b.dataset.feature)});
$$('.star').forEach(b=>b.onclick=()=>{rating=+b.dataset.value;$$('.star').forEach(s=>{s.classList.toggle('active',+s.dataset.value<=rating);s.setAttribute('aria-checked',+s.dataset.value===rating)});validate()});
select.onchange=()=>{const v=venues.find(x=>x.id===select.value);features.clear();$$('.check-item').forEach(b=>{const on=!!v?.attributes?.[b.dataset.feature];b.setAttribute('aria-pressed',on);if(on)features.add(b.dataset.feature)});validate()};
explanation.oninput=()=>$('#explanation-count').textContent=explanation.value.length;
function clearImage(){imageData=null;imageInput.value='';$('#image-preview').hidden=true;$('#upload-box').hidden=false;$('#preview-img').removeAttribute('src')}
$('#remove-image').onclick=clearImage;
async function compressImage(file){if(!['image/jpeg','image/png','image/webp'].includes(file.type))throw new Error('Format gambar harus JPG, PNG, atau WebP');if(file.size>5*1024*1024)throw new Error('Ukuran gambar maksimum 5 MB');const bitmap=await createImageBitmap(file),max=1280,scale=Math.min(1,max/Math.max(bitmap.width,bitmap.height)),canvas=document.createElement('canvas');canvas.width=Math.round(bitmap.width*scale);canvas.height=Math.round(bitmap.height*scale);canvas.getContext('2d').drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();return canvas.toDataURL('image/jpeg',.76)}
async function handleImage(file){if(!file)return;const box=$('#upload-box');box.querySelector('.upload-title').textContent='Memproses foto…';try{const dataUrl=await compressImage(file);if(dataUrl.length>900000)throw new Error('Foto masih terlalu besar setelah dikompres');imageData={dataUrl,name:file.name,type:'image/jpeg',originalSize:file.size};$('#preview-img').src=dataUrl;$('#image-name').textContent=file.name;$('#image-info').textContent=`${Math.round(dataUrl.length*0.75/1024)} KB setelah kompresi`;$('#image-preview').hidden=false;box.hidden=true}catch(e){alert(e.message);clearImage()}finally{box.querySelector('.upload-title').textContent='Unggah foto kondisi'}}
imageInput.onchange=()=>handleImage(imageInput.files[0]);const upload=$('#upload-box');['dragenter','dragover'].forEach(ev=>upload.addEventListener(ev,e=>{e.preventDefault();upload.classList.add('drag')}));['dragleave','drop'].forEach(ev=>upload.addEventListener(ev,e=>{e.preventDefault();upload.classList.remove('drag')}));upload.addEventListener('drop',e=>handleImage(e.dataTransfer.files[0]));
$('#audit-form').onsubmit=e=>{e.preventDefault();const v=venues.find(x=>x.id===select.value);if(!v){alert('Pilih lokasi terlebih dahulu.');return}let audits=[];try{audits=JSON.parse(localStorage.getItem('akseskota_audits')||'[]')}catch{}const audit={id:`audit-${Date.now()}-${Math.random().toString(36).slice(2,7)}`,locationId:v.id,locationName:v.name,rating,features:[...features],explanation:explanation.value.trim(),image:imageData,timestamp:new Date().toISOString(),status:'pending'};audits.push(audit);try{localStorage.setItem('akseskota_audits',JSON.stringify(audits))}catch{alert('Penyimpanan browser penuh. Hapus foto atau export/hapus audit lama.');audits.pop();return}localStorage.setItem('akseskota_score',String(audits.filter(a=>a.status==='approved').length*10));$('#submit').textContent='Audit terkirim';$('#submit').disabled=true;explanation.value='';$('#explanation-count').textContent='0';clearImage();stats();setTimeout(()=>{$('#submit').textContent='Kirim audit';validate()},1800)};
try{venues=await loadVenues();select.innerHTML='<option value="">Pilih lokasi…</option>'+venues.map(v=>`<option value="${v.id}">${v.name}</option>`).join('');const id=new URLSearchParams(location.search).get('venue');if(id&&venues.some(v=>v.id===id)){select.value=id;select.dispatchEvent(new Event('change'))}}catch{select.innerHTML='<option value="">Data gagal dimuat</option>'}stats();
