import{shell,initShell,initLogout,loadVenues,categories,featureLabels,initAnimations}from'./core.js?v=5';
import{getAccessibleRoute,routeProfileLabel}from'./accessible-routing.js';
import{isBusinessLocation,getBusinessForLocation,migrateSeedBusinessLocations,seedBusinessData}from'./business-store.js';
seedBusinessData();migrateSeedBusinessLocations();
document.querySelector('#shell').innerHTML=shell('map');initShell();initLogout();initAnimations();
const $=s=>document.querySelector(s);let venues=[],filtered=[],selected=null,userLocation=null,routeLayer=null,routeDestination=null,routeProfile='wheelchair',locationMarker=null;
const map=L.map('map',{center:[-6.225,106.822],zoom:12,zoomControl:false});
L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap'}).addTo(map);L.control.zoom({position:'bottomright'}).addTo(map);
const clusters=L.markerClusterGroup({showCoverageOnHover:false,maxClusterRadius:48,iconCreateFunction:c=>L.divIcon({className:'',html:`<div class="cluster-inner">${c.getChildCount()}</div>`,iconSize:[42,42]})}).addTo(map);
const markerById=new Map();
function icon(v){const c=categories[v.category]||categories.wheelchair_ramp;const biz=isBusinessLocation(v.id);const bizBadge=biz?'<div class="biz-marker-badge" title="Usaha Aksesibel"></div>':'';return L.divIcon({className:'',html:`<div class="marker-wrap">${bizBadge}<div class="custom-marker-inner" style="background:${c.color}"><span>${c.letter}</span></div></div>`,iconSize:[44,58],iconAnchor:[22,50]})}
function renderMarkers(){clusters.clearLayers();markerById.clear();filtered.forEach(v=>{const m=L.marker([v.lat,v.lng],{icon:icon(v),title:v.name}).on('click',()=>showDetail(v));markerById.set(v.id,m);clusters.addLayer(m)})}
function renderResults(){const box=$('#results');$('#result-meta').textContent=`${filtered.length} lokasi aktif`;box.innerHTML=filtered.slice(0,100).map(v=>{const c=categories[v.category]||categories.wheelchair_ramp;const sub=escapeHTML(locationSubtitle(v));return `<button class="result ${selected?.id===v.id?'active':''}" data-id="${v.id}"><span class="result-icon" style="color:${c.color}">${c.letter}</span><span><strong>${escapeHTML(v.name)}</strong><small>${sub} · ${escapeHTML(v.source||'OpenStreetMap')}</small></span></button>`}).join('');box.querySelectorAll('.result').forEach(b=>b.onclick=()=>focusVenue(venues.find(v=>v.id===b.dataset.id)))}
function escapeHTML(s=''){const d=document.createElement('div');d.textContent=s;return d.innerHTML}
const addrCache=new Map();let addrInflight=new Map();
async function reverseGeocode(lat,lng){const key=`${lat.toFixed(5)},${lng.toFixed(5)}`;if(addrCache.has(key))return addrCache.get(key);if(addrInflight.has(key))return addrInflight.get(key);const p=(async()=>{try{const res=await fetch(`https://nominatim.openstreetmap.org/reverse?format=jsonv2&lat=${lat}&lon=${lng}&zoom=18&accept-language=id`,{headers:{'Accept':'application/json'}});if(!res.ok)throw Error();const j=await res.json();const a=j.address||{};const road=a.road||a.pedestrian||a.footway||a.residential||'';const num=a.house_number?` ${a.house_number}`:'';const suburb=a.suburb||a.village||a.city_district||'';const city=a.city||a.county||'';const val=[road?`${road}${num}`:'',suburb,city].filter(Boolean).join(', ');addrCache.set(key,val);return val}catch{addrCache.set(key,'');return ''}finally{addrInflight.delete(key)}})();addrInflight.set(key,p);return p}
function locationSubtitle(v){return v.address&&v.address.trim()?v.address:`${v.lat.toFixed(5)}, ${v.lng.toFixed(5)}`}

function showDetail(v){selected=v;const c=categories[v.category]||categories.wheelchair_ramp;const features=Object.entries(v.attributes||{}).filter(([k])=>featureLabels[k]).map(([k,val])=>`<span class="feature ${val===true?'yes':''}">${val===true?'✓':val===false?'×':'?'} ${featureLabels[k]}</span>`).join('');const updated=v.osm_updated_at?new Date(v.osm_updated_at).toLocaleString('id-ID',{dateStyle:'medium',timeStyle:'short'}):'waktu tidak tersedia';const biz=getBusinessForLocation(v.id);const bizSection=biz?`<div class="detail-business"><span class="business-badge badge-${biz.badgeLevel||'bronze'}">Usaha Aksesibel — ${biz.badgeLevel==='platinum'?'Platinum':biz.badgeLevel==='gold'?'Emas':biz.badgeLevel==='silver'?'Perak':'Perunggu'}</span><small style="display:block;margin-top:6px;color:var(--muted)">Skor ${biz.score||0} · ${biz.reviewCount||0} review · ${biz.trend==='improving'?'Berkembang':biz.trend==='declining'?'Menurun':'Stabil'}</small></div>`:'';$('#detail').innerHTML=`<div class="detail-top"><div><span class="detail-category">${c.label} · ${escapeHTML((v.source||'OpenStreetMap').toUpperCase())}</span><h2>${escapeHTML(v.name)}</h2><p id="detail-addr">${escapeHTML(locationSubtitle(v))}</p></div><button class="detail-close" id="detail-close" aria-label="Tutup detail">×</button></div>${bizSection}<div class="feature-list">${features}</div><p><strong>${v.source==='Admin lokal'?'Data admin lokal':'Data real OSM'}</strong>${v.source==='Admin lokal'?'':' · diperbarui '+updated}</p><p class="validity-note"><strong>${v.source==='Admin lokal'?'Ditambahkan administrator lokal.':'Bersumber dari tag OpenStreetMap.'}</strong> Tanda ? berarti atribut belum dicatat. Kondisi fisik tetap perlu konfirmasi di lokasi.</p><div class="detail-actions"><button class="btn btn-outline" id="route-btn">Petunjuk arah</button><a class="btn btn-primary" href="audit.html?venue=${encodeURIComponent(v.id)}">Audit lokasi</a><button class="btn street-btn" id="street-btn" aria-label="Buka panorama 3D Street View di sekitar ${escapeHTML(v.name)}">Buka 3D Street View di tab baru </button></div>`;$('#detail').classList.add('open');if(!v.address||!v.address.trim()){reverseGeocode(v.lat,v.lng).then(a=>{const el=document.getElementById('detail-addr');if(el&&a)el.textContent=a})}$('#detail-close').onclick=()=>$('#detail').classList.remove('open');$('#route-btn').onclick=()=>routeTo(v);$('#street-btn').onclick=()=>openStreetView(v);renderResults()}
function openStreetView(v){const url=`https://www.google.com/maps/@?api=1&map_action=pano&viewpoint=${encodeURIComponent(v.lat)},${encodeURIComponent(v.lng)}`;window.open(url,'_blank','noopener,noreferrer')}
function focusVenue(v){if(!v)return;map.setView([v.lat,v.lng],16);const m=markerById.get(v.id);if(m)clusters.zoomToShowLayer(m,()=>m.fire('click'));if(innerWidth<861)$('#map-sidebar').classList.remove('open')}
function applyFilters(){const cat=$('.chip.active')?.dataset.category||'all',q=$('#search').value.trim().toLowerCase();filtered=venues.filter(v=>{if(q&&!v.name.toLowerCase().includes(q)&&!(v.address||'').toLowerCase().includes(q))return false;if(cat==='all')return true;if(cat==='business')return isBusinessLocation(v.id);return v.category===cat});renderMarkers();renderResults();if(q&&filtered.length===1)focusVenue(filtered[0])}
$('#category-chips').onclick=e=>{const chip=e.target.closest('.chip');if(!chip)return;document.querySelectorAll('.chip').forEach(c=>c.classList.toggle('active',c===chip));applyFilters()};$('#search-form').onsubmit=e=>{e.preventDefault();applyFilters()};$('#search').oninput=applyFilters;$('#expand-search').onclick=()=>$('#map-sidebar').classList.toggle('open');
function locate(){return new Promise((resolve,reject)=>{if(!navigator.geolocation){alert('Geolokasi tidak didukung browser ini.');reject(new Error('Geolokasi tidak didukung'));return}if(!window.isSecureContext){alert('Geolokasi butuh HTTPS atau localhost. Buka situs via URL aman, bukan IP publik HTTP.');reject(new Error('insecure'));return}const btn=$('#location-btn');btn.textContent='Mencari…';const opts={enableHighAccuracy:true,timeout:15000,maximumAge:0};navigator.geolocation.getCurrentPosition(p=>{const acc=Math.round(p.coords.accuracy);userLocation=[p.coords.latitude,p.coords.longitude];map.setView(userLocation,acc>80?14:16);if(locationMarker){map.removeLayer(locationMarker._group)}locationMarker={_group:L.layerGroup([L.circleMarker(userLocation,{radius:7,color:'#fff',weight:3,fillColor:'#2878b5',fillOpacity:1}).bindTooltip(`Lokasi Anda · ±${acc} m`).openTooltip(),L.circle(userLocation,{radius:acc,color:'#2878b5',weight:1,fillOpacity:.08})]).addTo(map)};btn.textContent='Lokasi saya';btn.title=`Akurasi ±${acc} m`;resolve(userLocation)},e=>{const msg={1:'Izin lokasi ditolak. Aktifkan izin lokasi di pengaturan browser, lalu coba lagi.',2:'Perangkat tidak dapat menentukan posisi. Pastikan layanan lokasi (GPS) aktif di perangkat.',3:'Waktu permintaan lokasi habis. Coba lagi di area terbuka.'}[e.code]||'Lokasi gagal diambil.';alert(msg);btn.textContent='Lokasi saya';reject(e)},opts)})}$('#location-btn').onclick=()=>locate().catch(()=>{});
function renderRoute(route){if(routeLayer)map.removeLayer(routeLayer);routeLayer=L.polyline(route.coordinates,{color:route.profile==='wheelchair'?'#176b45':'#2878b5',weight:7,opacity:.9,lineCap:'round'}).addTo(map);map.fitBounds(routeLayer.getBounds(),{padding:[55,55]});$('#route-summary').innerHTML=`<div><strong>${route.distanceKm<1?Math.round(route.distanceKm*1000)+' m':route.distanceKm.toFixed(1)+' km'}</strong><small>Jarak</small></div><div><strong>${route.durationMinutes} mnt</strong><small>Estimasi</small></div>`;$('#route-quality').innerHTML=route.warnings.map(w=>`<div class="route-warning">${escapeHTML(w)}</div>`).join('')+`<div class="route-engine">${escapeHTML(routeProfileLabel(route.profile))} · ${escapeHTML(route.engine)}</div>`;$('#route-steps').innerHTML=route.maneuvers.map((m,i)=>`<li><span class="route-step-num">${i+1}</span><span>${escapeHTML(m.instruction)}</span><small>${escapeHTML(m.distance)}</small></li>`).join('')}
async function calculateRoute(){if(!routeDestination)return;if(!userLocation){try{await locate()}catch{return}}$('#route-panel').classList.add('open');$('#detail').classList.remove('open');$('#route-loading').hidden=false;$('#route-summary').innerHTML='<div><strong>—</strong><small>Jarak</small></div><div><strong>—</strong><small>Estimasi</small></div>';$('#route-quality').innerHTML='';$('#route-steps').innerHTML='';try{const route=await getAccessibleRoute(userLocation,routeDestination,routeProfile);renderRoute(route)}catch(e){$('#route-quality').innerHTML=`<div class="route-warning"><strong>Rute gagal.</strong> ${escapeHTML(e.message)}</div>`}finally{$('#route-loading').hidden=true}}
function routeTo(v){routeDestination=v;$('#route-destination').textContent=v.name;$('#route-from').value='Lokasi saya';calculateRoute()}
document.querySelectorAll('[data-route-profile]').forEach(btn=>btn.onclick=()=>{routeProfile=btn.dataset.routeProfile;document.querySelectorAll('[data-route-profile]').forEach(b=>{const active=b===btn;b.classList.toggle('active',active);b.setAttribute('aria-checked',String(active))});calculateRoute()});
$('#route-close').onclick=()=>{$('#route-panel').classList.remove('open');if(routeLayer){map.removeLayer(routeLayer);routeLayer=null}};
async function loadRealData(fresh=false){const status=$('#data-status'),refresh=$('#refresh-data');refresh.disabled=true;status.querySelector('strong').textContent=fresh?'Memperbarui OpenStreetMap…':'Mengambil data OpenStreetMap…';try{venues=await loadVenues({fresh});filtered=[...venues];renderMarkers();renderResults();const bounds=L.latLngBounds(venues.map(v=>[v.lat,v.lng]));map.fitBounds(bounds,{padding:[30,30],maxZoom:13});const when=venues.updatedAt?new Date(venues.updatedAt).toLocaleString('id-ID',{dateStyle:'medium',timeStyle:'short'}):'baru saja';status.querySelector('strong').textContent=`Data peta aktif · ${venues.length} lokasi`;status.querySelector('span').textContent=`Snapshot OSM ${when}${venues.dataSource==='live'?' · live':' · cache 1 jam'}. Kondisi fisik dapat berubah.`}catch(e){status.querySelector('strong').textContent='Data real gagal dimuat';status.querySelector('span').textContent=e.message;$('#result-meta').textContent='Tidak ada data demo yang ditampilkan'}finally{refresh.disabled=false}}
$('#refresh-data').onclick=()=>loadRealData(true);
await loadRealData();
